### PR TITLE
Tweaks to the navbar highlight

### PR DESCRIPTION
**Pull request by cg505**
remove inset hover shadows
thin navbar shadow
put the bottom-border on hover on the inside and make it work for the brand

### CODE REVIEW

**Comment by cg505** [comment]
As mentioned in #67

**Comment by rye** [comment]
As I mentioned in #67, I'm not too much of a fan of completely removing the insets. I'll pull this and see how it feels.

**Comment by rye** [comment]
There we go. I like how it looks and feels right now. :shipit:, :sunglasses:

**Comment by cg505** [comment]
We could do the inset on active. Let me try that out.

**Comment by cg505** [comment]
How's that?

**Comment by rye** [comment]
I like it. Now :shipit: :D

**Pull request merged**
