### PR TITLE
Merge branch 'fixes' into 'master'

### PR DESCRIPTION
**Pull request by rye**
This applies some fixes which should go into the pseudo-public version.

### CODE REVIEW

**Comment by rye** [comment]
This would also constitute another patch release.

**Comment by Sammidysam** [comment]
We might want to look into a sticky footer, however.

**Comment by cg505** [comment]
Did the last one ever get released?

**Comment by Sammidysam** [comment]
Not that I know of.

**Comment by cg505** [comment]
Can someone who has their computer out do that then?

**Comment by cg505** [comment]
And then this one?

**Comment by rye** [comment]
I'll pull this up when I get home and make sure everything works, and then I'll likely merge (unless I receive any objections from anyone).

**Pull request merged**
