### PR TITLE
Merge branch 'fixes' into 'master'

### PR DESCRIPTION
**Pull request by rye**
Does this sound good to everyone? I'm not sure if stuff will die, but it looks like `fixes` was branched from `master`, so merging back should be A-okay.

### CODE REVIEW

**Comment by Sammidysam** [comment]
It can be automatically merged, which means that there are no merge conflicts.  Do you want this to be 0.1.2?

**Comment by rye** [comment]
I suppose all of the fixes could constitute a 0.1.2 release

**Comment by Sammidysam** [comment]
I think so, too.  Enough of them pertain to the end user anyway (and bug fixes are always nice).

**Comment by cg505** [comment]
Then let's merge it.

**Comment by rye** [comment]
Okay.

**Comment by cg505** [comment]
You doing the release?

**Comment by Sammidysam** [comment]
We should make the release.  I'll do so if I get time tomorrow, but if anybody else can, go ahead.  Also look at the new fixes and decide if they should be merged, too.

**Comment by cg505** [comment]
Go ahead.

**Pull request merged**
