### PR TITLE
Events

### PR DESCRIPTION
**Pull request by cg505**
Looks good?

### CODE REVIEW

**Comment by cg505** [comment]
Oh yeah, rake (obviously).

**Comment by rye** [comment]
Yeah, looks great.

**Comment by cg505** [comment]
Leave branch open?

I think from now on development can probably just happen on `backend`.

**Comment by rye** [comment]
Yeah, that sounds good.

**Comment by cg505** [comment]
Which sounds good? The first sentence was saying to keep it open, and the second to delete it.

**Comment by rye** [comment]
Doing development on backend now sounds good.

**Comment by Sammidysam** [comment]
I agree with everything.  We can use `backend` for backend, `visual-tweaks` for visual improvements, and `rails-bootstrap-navbar` if the navbar gem ever improves.

So only viewing all of the assignments and tests in one place (optionally events as well) needs to be done for 0.1.0 to be finished, right?

**Comment by cg505** [comment]
The docket controller does that, it's just ugly and bad right now.

**Pull request merged**
