### PR TITLE
Navbar accents

### PR DESCRIPTION
**Pull request by rye**
This adds some shadows and indicators to the navbar to set it apart from the rest of the page and make it a bit more obvious. It mainly uses box-shadows. Note that if it isn't working there are `-moz-box-shadow` and `-webkit-box-shadow` rules which can be paralleled with `box-shadow` to do stuffies.

@cg505, how do you like it? I think it's pretty schmexy.

### CODE REVIEW

**Comment by rye** [comment]
I also want @Sammidysam's opinion.

**Comment by Sammidysam** [comment]
Very pretty.  I like it.

**Comment by rye** [comment]
I don't know what @cg505's doing, but I'll go ahead and :shipit:.

**Comment by cg505** [comment]
Sorry, I was having a life for a little while. There's no reason not to also have the prefixes in there just in case. I do like how it looks, but I think it might be just a tad bit to bold. I'll open another pull request and see what you think.

**Comment by rye** [comment]
Okay. You can always decrease sizes and increase the color channel values if you want to make it less bold.

**Comment by cg505** [comment]
I actually would say that I like the main one under the navbar, but dislike the navbar hover insets. The design of this project so far has been completely flat. Raising the entire navbar but leaving the navbar itself flat runs with that theme. However, I think inset shadows on clicky things on hover creates an inconsistency that I dislike.

**Comment by cg505** [comment]
I do like the line under the hovered thing, though.

**Comment by rye** [comment]
I don't think you have to get rid of them completely, but whatever. I was thinking you could just make the hinting on that much less. Besides, the navbar is different from the everything else on the page, and we can totally add hinting to other stuff as well.

If you write something that works better, then that's :ok_hand:.

**Pull request merged**
