### PR TITLE
Reindent most of the tests.

### PR DESCRIPTION
**Pull request by rye**
I like tabs, and I think these were like this mistakenly. Just a simple mass indentation change. This will go direct to `master`.

I think I'll also clean up the test suite and start writing some tests.

### CODE REVIEW

**Comment by cg505** [comment]
There's a lot of code style cleanup. I like the idea of it happening on master (or basically on master) because it will probably reduce merge conflicts overall.

**Comment by rye** [comment]
Yeah. This branch was directly created off of master. Look good?

**Comment by rye** [comment]
If so, I'll :shipit:.

**Comment by rye** [comment]
Meh, it's only a coding style change. You can always revert if you disapprove.

**Comment by cg505** [comment]
:+1:

**Comment by rye** [comment]
:cool:

**Pull request merged**
