### PR TITLE
Collapse the weekend by default

### PR DESCRIPTION
**Pull request by cg505**
This was a thought I had. Do you think it is a good idea?

### CODE REVIEW

**Comment by rye** [comment]
Looks nice, though if we'll be getting rid of this and making new views it doesn't matter that much. If it's stable, :ship: it.

**Comment by rye** [comment]
And it looks stable, so :shipit:.

**Comment by rye** [comment]
I'll go ahead and do it for you :).

**Comment by cg505** [comment]
:sunglasses:

**Pull request merged**
